version: '3.9'

services:
    ####################################################################
    # PostgreSQL database                                              #
    ####################################################################
    postgres:
        image: postgres:14-alpine
        ports:
            - 5432:5432
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_PASS}
volumes:
    db:
