version: '3.9'

services:
  # ####################################################################
  # # API backend service                                              #
  # ####################################################################
  banking-api:
    depends_on:
      - postgres
    container_name: banking-api
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
      # target: development
    volumes:
      # - '/app/node_modules'
      # - '.:/usr/src/app'
      - banking-api:/usr/src/app
    env_file:
      - .env
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - banking-network
  #     user: node
  ####################################################################
  # PostgreSQL database                                              #
  ####################################################################
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
    networks:
      - banking-network
networks:
  banking-network:
    driver: bridge
volumes:
  db:
  banking-api:
